# Generated by Django 5.2.17 on 2026-10-04 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('planning', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('unit', models.CharField(max_length=50, verbose_name='единица измерения')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена за единицу')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Выполнено'), ('CANCELLED', 'Отменено')], default='PLANNED', max_length=20, verbose_name='статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='projects.section', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'работа проекта',
                'verbose_name_plural': 'работы проекта',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('unit', models.CharField(max_length=50, verbose_name='единица измерения')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='вес (%)')),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='плановый объем')),
                ('labor_norm_per_unit', models.DecimalField(decimal_places=3, default=0, help_text='Сколько чел-часов нужно на 1 единицу объёма', max_digits=8, verbose_name='норматив трудозатрат, чел-час/ед')),
                ('default_brigade', models.CharField(blank=True, help_text='Например: Бригада изолировщиков №1', max_length=150, verbose_name='бригада по умолчанию')),
                ('labor_hourly_rate', models.DecimalField(decimal_places=2, default=350, max_digits=10, verbose_name='ставка рабочего, ₽/час')),
                ('equipment_norm_per_unit', models.DecimalField(decimal_places=3, default=0, help_text='Сколько машино-часов нужно на 1 единицу объёма', max_digits=8, verbose_name='норматив техники, маш-час/ед')),
                ('default_equipment', models.CharField(blank=True, help_text='Например: Экскаватор JCB 3CX', max_length=150, verbose_name='техника по умолчанию')),
                ('equipment_hourly_rate', models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='ставка техники, ₽/маш-час')),
                ('fuel_norm_per_unit', models.DecimalField(decimal_places=3, default=0, help_text='Сколько литров топлива нужно на 1 единицу объёма', max_digits=8, verbose_name='норматив ГСМ, л/ед')),
                ('fuel_price', models.DecimalField(decimal_places=2, default=65, max_digits=8, verbose_name='цена топлива, ₽/л')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('load_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_work_items', to='planning.loadprofile', verbose_name='профиль нагрузки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='works.projectworkitem', verbose_name='родитель')),
                ('project_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='works.projectwork', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'элемент работы',
                'verbose_name_plural': 'элементы работ',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('unit', models.CharField(max_length=50, verbose_name='единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'шаблон работы',
                'verbose_name_plural': 'шаблоны работ',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='projectwork',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_works', to='works.worktemplate', verbose_name='шаблон'),
        ),
        migrations.CreateModel(
            name='WorkTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('version_number', models.PositiveIntegerField(verbose_name='номер версии')),
                ('is_current', models.BooleanField(default=False, verbose_name='текущая версия')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='создано')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='works.worktemplate', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'версия шаблона',
                'verbose_name_plural': 'версии шаблонов',
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='WorkTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('unit', models.CharField(max_length=50, verbose_name='единица измерения')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='вес (%)')),
                ('normative', models.JSONField(blank=True, default=dict, verbose_name='нормативы')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('load_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='planning.loadprofile', verbose_name='профиль нагрузки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='works.worktemplateitem', verbose_name='родитель')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='works.worktemplateversion', verbose_name='версия')),
            ],
            options={
                'verbose_name': 'элемент шаблона',
                'verbose_name_plural': 'элементы шаблонов',
                'ordering': ['sequence'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectwork',
            unique_together={('section', 'code')},
        ),
    ]
