# Generated by Django 5.2.17 on 2026-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktemplateitem',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Сколько единиц подработы нужно на 1 единицу работы', max_digits=10, verbose_name='норматив подработы'),
        ),
    ]
