# Generated by Django 5.2.17 on 2026-10-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_worktemplateitem_quantity_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkitem',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Сколько единиц подработы нужно на 1 единицу работы', max_digits=10, verbose_name='норматив подработы'),
        ),
        migrations.AddField(
            model_name='worktemplateitem',
            name='equipment_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='ставка техники, ₽/маш-час'),
        ),
        migrations.AddField(
            model_name='worktemplateitem',
            name='equipment_norm_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Сколько машино-часов нужно на 1 единицу объёма подработы', max_digits=8, verbose_name='норматив техники, маш-час/ед'),
        ),
        migrations.AddField(
            model_name='worktemplateitem',
            name='fuel_norm_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Сколько литров топлива нужно на 1 единицу объёма подработы', max_digits=8, verbose_name='норматив ГСМ, л/ед'),
        ),
        migrations.AddField(
            model_name='worktemplateitem',
            name='fuel_price',
            field=models.DecimalField(decimal_places=2, default=65, max_digits=8, verbose_name='цена топлива, ₽/л'),
        ),
        migrations.AddField(
            model_name='worktemplateitem',
            name='labor_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=10, verbose_name='ставка рабочего, ₽/час'),
        ),
        migrations.AddField(
            model_name='worktemplateitem',
            name='labor_norm_per_unit',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Сколько чел-часов нужно на 1 единицу объёма подработы', max_digits=8, verbose_name='норматив трудозатрат, чел-час/ед'),
        ),
        migrations.AlterField(
            model_name='projectworkitem',
            name='planned_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='плановый объем'),
        ),
    ]
