# Generated by Django 5.2.18 on 2026-10-06 16:14

import django.db.models.deletion
from django.db import migrations, models


def classify_work(apps, schema_editor):
    Work = apps.get_model('works', 'ProjectWork')
    Item = apps.get_model('works', 'ProjectWorkItem')
    alias = schema_editor.connection.alias
    ids = Item.objects.using(alias).values_list('project_work_id', flat=True).distinct()
    Work.objects.using(alias).filter(pk__in=ids).update(kind='COMPOSITE')


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_globalplanversion_alter_dailyplan_unique_together_and_more'),
        ('works', '0003_projectworkitem_quantity_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwork',
            name='allow_fractional',
            field=models.BooleanField(default=True, verbose_name='Учитывать дробные единицы'),
        ),
        migrations.AddField(
            model_name='projectwork',
            name='kind',
            field=models.CharField(choices=[('SIMPLE', 'Простая'), ('COMPOSITE', 'Составная')], default='SIMPLE', max_length=12, verbose_name='Вид работы'),
        ),
        migrations.AddField(
            model_name='projectwork',
            name='load_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.loadprofile', verbose_name='Профиль простой работы'),
        ),
    ]

    operations += [migrations.RunPython(classify_work, migrations.RunPython.noop)]
