# Generated by Django 5.2.18 on 2026-10-06 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_standard_roles'),
        ('works', '0004_projectwork_allow_fractional_projectwork_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'группа работ',
                'verbose_name_plural': 'группы работ',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='projectwork',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.workgroup', verbose_name='Группа работ'),
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('symbol', models.CharField(max_length=50, verbose_name='Обозначение')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'единица измерения',
                'verbose_name_plural': 'единицы измерения',
                'ordering': ['symbol'],
                'constraints': [models.UniqueConstraint(fields=('company', 'symbol'), name='unique_company_measurement_unit')],
            },
        ),
        migrations.AddConstraint(
            model_name='workgroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_work_group'),
        ),
    ]
