# Generated by Django 5.2.18 on 2026-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_seed_measurement_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectwork',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='worktemplate',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='код'),
        ),
    ]
