# Generated by Django 5.2.18 on 2026-10-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_approval_roles'),
        ('works', '0007_alter_projectwork_code_alter_worktemplate_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkMergeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merge_origin', to='works.projectworkitem')),
                ('source_work', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merged_source', to='works.projectwork')),
            ],
            options={
                'verbose_name': 'источник объединённой работы',
                'verbose_name_plural': 'источники объединённых работ',
            },
        ),
    ]
