# Generated by Django 5.2.18 on 2026-10-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_approval_roles'),
        ('planning', '0013_workmonthallocation_daily_override'),
        ('works', '0008_workmergesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkMergePlanRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('seed_snapshot', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('parent_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_plan_revisions', to='works.projectwork')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_revisions', to='planning.globalplanversion')),
                ('target_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_revision', to='planning.globalplanversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
