# Generated by Django 5.2.18 on 2026-10-07 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def initial_prices(apps, schema_editor):
    from datetime import date

    Work = apps.get_model("works", "ProjectWork")
    Price = apps.get_model("works", "WorkPrice")
    Price.objects.using(schema_editor.connection.alias).bulk_create(
        [
            Price(
                company_id=work.company_id,
                work_id=work.pk,
                price=work.unit_price,
                effective_from=date.min,
                reason="Первоначальная цена при включении истории; более ранние цены неизвестны",
            )
            for work in Work.objects.using(schema_editor.connection.alias)
            .all()
            .iterator()
        ],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_approval_roles"),
        ("works", "0009_workmergeplanrevision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Цена за единицу, ₽",
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Действует с")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Основание"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="accounts.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "corrects",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="works.workprice",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_price_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="works.projectwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "история цены работы",
                "ordering": ["effective_from", "pk"],
                "indexes": [
                    models.Index(
                        fields=["work", "effective_from"],
                        name="works_workp_work_id_487168_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(initial_prices, migrations.RunPython.noop),
    ]
