# Generated by Django 5.2.17 on 2026-10-04 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('planning', '0002_initial'),
        ('projects', '0001_initial'),
        ('resources', '0001_initial'),
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'причина отклонения',
                'verbose_name_plural': 'причины отклонений',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FuelFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Дизельное топливо'), ('PETROL_92', 'Бензин АИ-92'), ('PETROL_95', 'Бензин АИ-95'), ('PETROL_98', 'Бензин АИ-98'), ('GAS', 'Газ (пропан/метан)'), ('OIL', 'Масло моторное'), ('OTHER', 'Другое')], default='DIESEL', max_length=20, verbose_name='вид ГСМ')),
                ('planned_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='план, л')),
                ('actual_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='факт, л')),
                ('price_per_liter', models.DecimalField(decimal_places=2, default=0, help_text='Актуальная цена за литр на дату списания', max_digits=8, verbose_name='цена за литр, ₽')),
                ('equipment_ref', models.CharField(blank=True, help_text='На какую технику/бригаду списано топливо', max_length=150, verbose_name='привязка к технике')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('project_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_facts', to='works.projectwork', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'факт по ГСМ',
                'verbose_name_plural': 'факты по ГСМ',
                'ordering': ['-date', 'fuel_type'],
            },
        ),
        migrations.CreateModel(
            name='FuelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Дизельное топливо'), ('PETROL_92', 'Бензин АИ-92'), ('PETROL_95', 'Бензин АИ-95'), ('PETROL_98', 'Бензин АИ-98'), ('GAS', 'Газ (пропан/метан)'), ('OIL', 'Масло моторное'), ('OTHER', 'Другое')], default='DIESEL', max_length=20, verbose_name='вид ГСМ')),
                ('planned_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='план, л')),
                ('price_per_liter', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена за литр, ₽')),
                ('equipment_ref', models.CharField(blank=True, max_length=150, verbose_name='привязка к технике')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_plans', to='planning.planversion', verbose_name='версия плана')),
                ('project_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_plans', to='works.projectwork', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'план по ГСМ',
                'verbose_name_plural': 'планы по ГСМ',
                'ordering': ['date', 'fuel_type'],
            },
        ),
        migrations.CreateModel(
            name='DailyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('actual_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='фактический объём')),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='фактическая стоимость')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('project_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_facts', to='works.projectwork', verbose_name='работа')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_facts', to=settings.AUTH_USER_MODEL, verbose_name='внёс')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_facts', to='works.projectworkitem', verbose_name='подработа')),
                ('deviation_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='production.deviationreason', verbose_name='причина отклонения')),
            ],
            options={
                'verbose_name': 'дневной факт',
                'verbose_name_plural': 'дневные факты',
                'ordering': ['-date', 'project_work'],
                'unique_together': {('project_work', 'work_item', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('equipment_type', models.CharField(help_text='Например: Экскаватор JCB 3CX, Кран Ивановец 25т', max_length=150, verbose_name='вид техники')),
                ('equipment_number', models.CharField(blank=True, help_text='Государственный регистрационный номер или инвентарный', max_length=50, verbose_name='гос. номер / инв. №')),
                ('planned_count', models.IntegerField(default=0, verbose_name='план, ед')),
                ('actual_count', models.IntegerField(default=0, verbose_name='факт, ед')),
                ('machine_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='машино-часы')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Стоимость машино-часа', max_digits=10, verbose_name='ставка, ₽/маш-час')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('project_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_facts', to='works.projectwork', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'факт по технике',
                'verbose_name_plural': 'факты по технике',
                'ordering': ['-date', 'equipment_type'],
                'unique_together': {('project_work', 'date', 'equipment_type', 'equipment_number')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('equipment_type', models.CharField(help_text='Например: Экскаватор JCB 3CX', max_length=150, verbose_name='вид техники')),
                ('equipment_number', models.CharField(blank=True, max_length=50, verbose_name='гос. номер / инв. №')),
                ('planned_count', models.IntegerField(default=0, verbose_name='план, ед')),
                ('planned_machine_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='план, маш-час')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ставка, ₽/маш-час')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_plans', to='planning.planversion', verbose_name='версия плана')),
                ('project_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_plans', to='works.projectwork', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'план по технике',
                'verbose_name_plural': 'планы по технике',
                'ordering': ['date', 'equipment_type'],
                'unique_together': {('project_work', 'date', 'equipment_type', 'equipment_number')},
            },
        ),
        migrations.CreateModel(
            name='LaborFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('planned_workers', models.IntegerField(default=0, verbose_name='план, чел')),
                ('actual_workers', models.IntegerField(default=0, verbose_name='факт, чел')),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='план, чел-час')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='факт, чел-час')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ставка, ₽/час')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_facts', to='resources.brigade', verbose_name='бригада')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_facts', to='projects.project', verbose_name='проект')),
                ('project_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_facts', to='works.projectwork', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'факт по людям',
                'verbose_name_plural': 'факты по людям',
                'ordering': ['-date', 'brigade'],
                'unique_together': {('project_work', 'date', 'brigade')},
            },
        ),
        migrations.CreateModel(
            name='LaborPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('planned_workers', models.IntegerField(default=0, verbose_name='план, чел')),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='план, чел-час')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ставка, ₽/час')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_plans', to='resources.brigade', verbose_name='бригада')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_plans', to='planning.planversion', verbose_name='версия плана')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_plans', to='projects.project', verbose_name='проект')),
                ('project_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_plans', to='works.projectwork', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'план по людям',
                'verbose_name_plural': 'планы по людям',
                'ordering': ['date', 'brigade'],
                'unique_together': {('project_work', 'date', 'brigade')},
            },
        ),
    ]
