# Generated by Django 5.2.17 on 2026-10-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('projects', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborfact',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_facts', to='projects.project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='laborfact',
            name='project_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_facts', to='works.projectwork', verbose_name='работа'),
        ),
        migrations.AlterField(
            model_name='laborplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_plans', to='projects.project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='laborplan',
            name='project_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_plans', to='works.projectwork', verbose_name='работа'),
        ),
    ]
