# Generated by Django 5.2.17 on 2026-10-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_laborfact_project_alter_laborfact_project_work_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laborfact',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='laborfact',
            name='actual_workers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='факт, чел'),
        ),
        migrations.AlterField(
            model_name='laborfact',
            name='planned_workers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='план, чел'),
        ),
    ]
