# Generated by Django 5.2.17 on 2026-10-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_laborfact_unique_together_and_more'),
        ('projects', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentfact',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equipmentfact',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_facts', to='projects.project', verbose_name='проект'),
        ),
        migrations.AddField(
            model_name='equipmentplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_plans', to='projects.project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='equipmentfact',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ставка, ₽/маш-час'),
        ),
        migrations.AlterField(
            model_name='equipmentfact',
            name='machine_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='машино-часы'),
        ),
        migrations.AlterField(
            model_name='equipmentfact',
            name='project_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_facts', to='works.projectwork', verbose_name='работа'),
        ),
        migrations.AlterField(
            model_name='equipmentplan',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ставка, ₽/маш-час'),
        ),
        migrations.AlterField(
            model_name='equipmentplan',
            name='planned_machine_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='план, маш-час'),
        ),
        migrations.AlterField(
            model_name='equipmentplan',
            name='project_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_plans', to='works.projectwork', verbose_name='работа'),
        ),
    ]
