# Generated by Django 5.2.17 on 2026-10-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_equipmentfact_unique_together_and_more'),
        ('projects', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelfact',
            name='planned_liters',
        ),
        migrations.AddField(
            model_name='fuelfact',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_facts', to='projects.project', verbose_name='проект'),
        ),
        migrations.AddField(
            model_name='fuelplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_plans', to='projects.project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='fuelfact',
            name='equipment_ref',
            field=models.CharField(blank=True, max_length=150, verbose_name='привязка к технике'),
        ),
        migrations.AlterField(
            model_name='fuelfact',
            name='price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='цена за литр, ₽'),
        ),
        migrations.AlterField(
            model_name='fuelfact',
            name='project_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_facts', to='works.projectwork', verbose_name='работа'),
        ),
        migrations.AlterField(
            model_name='fuelplan',
            name='price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='цена за литр, ₽'),
        ),
        migrations.AlterField(
            model_name='fuelplan',
            name='project_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_plans', to='works.projectwork', verbose_name='работа'),
        ),
    ]
