# Generated by Django 5.2.17 on 2026-10-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_fuelfact_planned_liters_fuelfact_project_and_more'),
        ('resources', '0002_alter_equipmenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentfact',
            options={'ordering': ['-date', 'equipment_type__name'], 'verbose_name': 'факт по технике', 'verbose_name_plural': 'факты по технике'},
        ),
        migrations.AlterModelOptions(
            name='equipmentplan',
            options={'ordering': ['date', 'equipment_type__name'], 'verbose_name': 'план по технике', 'verbose_name_plural': 'планы по технике'},
        ),
        migrations.AlterField(
            model_name='equipmentfact',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_facts', to='resources.equipmenttype', verbose_name='вид техники'),
        ),
        migrations.AlterField(
            model_name='equipmentplan',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_plans', to='resources.equipmenttype', verbose_name='вид техники'),
        ),
    ]
