# Generated by Django 5.2.18 on 2026-10-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_objects(apps, schema_editor):
    import json
    from collections import defaultdict
    from django.core.serializers.json import DjangoJSONEncoder
    alias = schema_editor.connection.alias
    Object = apps.get_model('projects', 'ConstructionObject')
    Work = apps.get_model('works', 'ProjectWork')
    Archive = apps.get_model('production', 'LegacyResourceRecord')
    for name in ('LaborPlan', 'EquipmentPlan', 'FuelPlan', 'LaborFact', 'EquipmentFact', 'FuelFact'):
        Model = apps.get_model('production', name)
        mapped = {}
        groups = defaultdict(list)
        records = list(Model.objects.using(alias).all())
        for row in records:
            candidates = set()
            work_id = row.project_work_id
            if not work_id and hasattr(row, 'plan_version_id') and row.plan_version_id:
                work_id = row.plan_version.monthly_plan.project_work_id
            if work_id:
                work = Work.objects.using(alias).select_related('section__construction_object').get(pk=work_id)
                obj = work.section.construction_object
                if work.company_id == row.company_id and obj.company_id == row.company_id and (not row.project_id or obj.project_id == row.project_id):
                    candidates.add(obj.pk)
            elif row.project_id:
                candidates.update(Object.objects.using(alias).filter(project_id=row.project_id, company_id=row.company_id).values_list('pk', flat=True))
            object_id = next(iter(candidates)) if len(candidates) == 1 else None
            if name.startswith('Labor') and row.brigade.company_id != row.company_id:
                object_id = None
            if name.startswith('Equipment') and row.equipment_type.company_id != row.company_id:
                object_id = None
            mapped[row.pk] = object_id
            key = (object_id, row.date)
            if name.startswith('Labor'):
                key += (row.brigade_id,)
            elif name.startswith('Equipment'):
                key += (row.equipment_type_id, row.equipment_number)
            else:
                key += (row.fuel_type, row.equipment_ref)
            if object_id:
                groups[key].append(row.pk)
        conflicts = {pk for group in groups.values() if len(group) > 1 for pk in group}
        for row in records:
            obj_id = mapped[row.pk]
            resolved = bool(obj_id) and row.pk not in conflicts
            payload = {field.attname: getattr(row, field.attname) for field in Model._meta.fields}
            Archive.objects.using(alias).create(
                company_id=row.company_id, source_model=name, source_pk=row.pk,
                payload=json.loads(json.dumps(payload, cls=DjangoJSONEncoder)),
                reason='Автоматический перенос' if resolved else 'Совпадают объект, дата и ресурс; требуется ручное объединение' if row.pk in conflicts else 'Объект нельзя определить однозначно',
                resolved=resolved, construction_object_id=obj_id if resolved else None,
                restored_pk=row.pk if resolved else None,
            )
            if resolved:
                Model.objects.using(alias).filter(pk=row.pk).update(construction_object_id=obj_id)
            else:
                # Original fields remain intact in Archive; unresolved data is not assigned arbitrarily.
                Model.objects.using(alias).filter(pk=row.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('production', '0006_alter_equipmentfact_options_and_more'),
        ('projects', '0001_initial'),
        ('resources', '0002_alter_equipmenttype_options_and_more'),
        ('works', '0004_projectwork_allow_fractional_projectwork_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    original_operations = [
        migrations.CreateModel(
            name='LegacyResourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source_model', models.CharField(max_length=50, verbose_name='Тип записи')),
                ('source_pk', models.PositiveIntegerField(verbose_name='Исходный ID')),
                ('payload', models.JSONField(default=dict, verbose_name='Исходные данные')),
                ('reason', models.TextField(verbose_name='Причина ручного назначения')),
                ('resolved', models.BooleanField(default=False, verbose_name='Назначен объект')),
                ('restored_pk', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['source_model', 'source_pk'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyfact',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentfact',
            unique_together={('construction_object', 'date', 'equipment_type', 'equipment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentplan',
            unique_together={('construction_object', 'date', 'equipment_type', 'equipment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='fuelfact',
            unique_together={('construction_object', 'date', 'fuel_type', 'equipment_ref')},
        ),
        migrations.AlterUniqueTogether(
            name='fuelplan',
            unique_together={('construction_object', 'date', 'fuel_type', 'equipment_ref')},
        ),
        migrations.AlterUniqueTogether(
            name='laborfact',
            unique_together={('construction_object', 'date', 'brigade')},
        ),
        migrations.AlterUniqueTogether(
            name='laborplan',
            unique_together={('construction_object', 'date', 'brigade')},
        ),
        migrations.AddField(
            model_name='equipmentfact',
            name='construction_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='projects.constructionobject', verbose_name='Строительный объект'),
        ),
        migrations.AddField(
            model_name='equipmentplan',
            name='construction_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='projects.constructionobject', verbose_name='Строительный объект'),
        ),
        migrations.AddField(
            model_name='fuelfact',
            name='construction_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='projects.constructionobject', verbose_name='Строительный объект'),
        ),
        migrations.AddField(
            model_name='fuelplan',
            name='construction_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='projects.constructionobject', verbose_name='Строительный объект'),
        ),
        migrations.AddField(
            model_name='laborfact',
            name='construction_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='projects.constructionobject', verbose_name='Строительный объект'),
        ),
        migrations.AddField(
            model_name='laborplan',
            name='construction_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='projects.constructionobject', verbose_name='Строительный объект'),
        ),
        migrations.AddConstraint(
            model_name='dailyfact',
            constraint=models.UniqueConstraint(condition=models.Q(('work_item__isnull', False)), fields=('project_work', 'work_item', 'date'), name='unique_item_fact'),
        ),
        migrations.AddConstraint(
            model_name='dailyfact',
            constraint=models.UniqueConstraint(condition=models.Q(('work_item__isnull', True)), fields=('project_work', 'date'), name='unique_simple_fact'),
        ),
        migrations.AddField(
            model_name='legacyresourcerecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='legacyresourcerecord',
            name='construction_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.constructionobject'),
        ),
        migrations.RemoveField(
            model_name='equipmentfact',
            name='project',
        ),
        migrations.RemoveField(
            model_name='equipmentfact',
            name='project_work',
        ),
        migrations.RemoveField(
            model_name='equipmentplan',
            name='plan_version',
        ),
        migrations.RemoveField(
            model_name='equipmentplan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='equipmentplan',
            name='project_work',
        ),
        migrations.RemoveField(
            model_name='fuelfact',
            name='project',
        ),
        migrations.RemoveField(
            model_name='fuelfact',
            name='project_work',
        ),
        migrations.RemoveField(
            model_name='fuelplan',
            name='plan_version',
        ),
        migrations.RemoveField(
            model_name='fuelplan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='fuelplan',
            name='project_work',
        ),
        migrations.RemoveField(
            model_name='laborfact',
            name='project',
        ),
        migrations.RemoveField(
            model_name='laborfact',
            name='project_work',
        ),
        migrations.RemoveField(
            model_name='laborplan',
            name='plan_version',
        ),
        migrations.RemoveField(
            model_name='laborplan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='laborplan',
            name='project_work',
        ),
        migrations.AlterUniqueTogether(
            name='legacyresourcerecord',
            unique_together={('source_model', 'source_pk')},
        ),
    ]

    operations = [op for op in original_operations if isinstance(op, (migrations.CreateModel, migrations.AddField))]
    operations += [migrations.RunPython(migrate_objects)]
    operations += [op for op in original_operations if not isinstance(op, (migrations.CreateModel, migrations.AddField))]
    operations += [migrations.AlterField(
        model_name=name.lower(), name='construction_object',
        field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='projects.constructionobject', verbose_name='Строительный объект'),
    ) for name in ('LaborPlan', 'EquipmentPlan', 'FuelPlan', 'LaborFact', 'EquipmentFact', 'FuelFact')]
