# Generated by Django 5.2.18 on 2026-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_legacyresourcerecord_alter_dailyfact_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviationreason',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='код'),
        ),
    ]
