# Generated by Django 5.2.18 on 2026-10-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_deviationreason_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelfact',
            name='equipment_ref',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='привязка к технике'),
        ),
        migrations.AlterField(
            model_name='fuelplan',
            name='equipment_ref',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='привязка к технике'),
        ),
    ]
