# Generated by Django 5.2.18 on 2026-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_fuelfact_equipment_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelfact',
            name='actual_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Остаток, л'),
        ),
        migrations.AddField(
            model_name='fuelplan',
            name='planned_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Остаток, л'),
        ),
        migrations.AlterField(
            model_name='fuelfact',
            name='actual_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расход за день, л'),
        ),
        migrations.AlterField(
            model_name='fuelplan',
            name='planned_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расход за день, л'),
        ),
    ]
