# Generated by Django 5.2.17 on 2026-10-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код проекта')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('ARCHIVED', 'Архивный'), ('CLOSED', 'Закрытый')], default='ACTIVE', max_length=20, verbose_name='статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ConstructionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.constructionobject', verbose_name='родительский объект')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_objects', to='projects.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'строительный объект',
                'verbose_name_plural': 'строительные объекты',
                'ordering': ['name'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('construction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.constructionobject', verbose_name='строительный объект')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
                'ordering': ['name'],
                'unique_together': {('construction_object', 'code')},
            },
        ),
    ]
