# Generated by Django 5.2.18 on 2026-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='код проекта'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='код'),
        ),
    ]
