# Generated by Django 5.2.18 on 2026-10-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_objects',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='projects.constructionobject', verbose_name='назначенные строительные объекты'),
        ),
    ]
