# Generated by Django 5.2.17 on 2026-10-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='Уникальный код, например: БР-001', max_length=20, verbose_name='код бригады')),
                ('name', models.CharField(max_length=150, verbose_name='название бригады')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'бригада',
                'verbose_name_plural': 'бригады',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ставка за час')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'тип техники',
                'verbose_name_plural': 'типы техники',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ставка по умолчанию')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='resources.position', verbose_name='должность')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BrigadeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role_in_brigade', models.CharField(blank=True, max_length=100, verbose_name='роль в бригаде')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='resources.brigade', verbose_name='бригада')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brigade_memberships', to='resources.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'член бригады',
                'verbose_name_plural': 'члены бригад',
                'unique_together': {('brigade', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('plate_number', models.CharField(max_length=50, verbose_name='гос. номер')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='resources.equipmenttype', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'техника',
                'verbose_name_plural': 'техника',
                'ordering': ['plate_number'],
                'unique_together': {('company', 'plate_number')},
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('unit', models.CharField(default='л', max_length=20, verbose_name='единица измерения')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена по умолчанию')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'тип топлива',
                'verbose_name_plural': 'типы топлива',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
