# Generated by Django 5.2.17 on 2026-10-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['name'], 'verbose_name': 'вид техники', 'verbose_name_plural': 'виды техники'},
        ),
        migrations.AlterUniqueTogether(
            name='equipmenttype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='category',
            field=models.CharField(blank=True, help_text='Например: Землеройная, Подъёмная, Транспортная', max_length=100, verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='default_hourly_rate',
        ),
    ]
