# Generated by Django 5.2.18 on 2026-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_equipmenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Уникальный код, например: БР-001', max_length=20, verbose_name='код бригады'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='код'),
        ),
    ]
