# Generated by Django 5.2.18 on 2026-10-06 22:30

import django.db.models.deletion
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    EquipmentType = apps.get_model('resources', 'EquipmentType')
    Category = apps.get_model('resources', 'EquipmentCategory')
    alias = schema_editor.connection.alias
    for equipment_type in EquipmentType.objects.using(alias).all().iterator():
        name = equipment_type.legacy_category.strip()
        if name:
            category, _ = Category.objects.using(alias).get_or_create(company_id=equipment_type.company_id, name=name)
            EquipmentType.objects.using(alias).filter(pk=equipment_type.pk).update(category_id=category.pk)


def restore_categories(apps, schema_editor):
    EquipmentType = apps.get_model('resources', 'EquipmentType')
    alias = schema_editor.connection.alias
    for equipment_type in EquipmentType.objects.using(alias).select_related('category').all().iterator():
        EquipmentType.objects.using(alias).filter(pk=equipment_type.pk).update(
            legacy_category=equipment_type.category.name if equipment_type.category_id else '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_standard_roles'),
        ('resources', '0003_alter_brigade_code_alter_fueltype_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'категория техники',
                'verbose_name_plural': 'категории техники',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(model_name='equipmenttype', old_name='category', new_name='legacy_category'),
        migrations.AddField(
            model_name='equipmenttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_types', to='resources.equipmentcategory', verbose_name='категория'),
        ),
        migrations.RunPython(migrate_categories, restore_categories),
        migrations.RemoveField(model_name='equipmenttype', name='legacy_category'),
        migrations.AddConstraint(
            model_name='equipmentcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_equipment_category_name'),
        ),
    ]
