# Generated by Django 5.2.18 on 2026-10-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_equipmentcategory_alter_equipmenttype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='unit',
            field=models.CharField(default='ед.', max_length=50, verbose_name='единица измерения'),
        ),
    ]
