# Generated by Django 5.2.18 on 2026-10-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_brigadegroup_brigade_group_brigademacrogroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigade',
            name='unit',
            field=models.CharField(default='чел.', max_length=50, verbose_name='единица измерения'),
        ),
    ]
