# Generated by Django 5.2.17 on 2026-10-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('workday_number', models.PositiveIntegerField(verbose_name='номер рабочего дня')),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='плановый объем')),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='плановая стоимость')),
            ],
            options={
                'verbose_name': 'дневной план',
                'verbose_name_plural': 'дневные планы',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LoadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'профиль нагрузки',
                'verbose_name_plural': 'профили нагрузки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoadProfileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('workday_number', models.PositiveIntegerField(verbose_name='номер рабочего дня')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='процент')),
            ],
            options={
                'verbose_name': 'элемент профиля',
                'verbose_name_plural': 'элементы профиля',
                'ordering': ['workday_number'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('year', models.PositiveIntegerField(verbose_name='год')),
                ('month', models.PositiveIntegerField(verbose_name='месяц')),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='плановый объем')),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='плановая стоимость')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
                ('mismatch_strategy', models.CharField(choices=[('STRETCH', 'Растянуть'), ('COMPRESS', 'Сжать'), ('TRUNCATE', 'Обрезать'), ('STRICT', 'Строгий режим')], default='STRICT', max_length=20, verbose_name='стратегия при несовпадении дней')),
            ],
            options={
                'verbose_name': 'месячный план',
                'verbose_name_plural': 'месячные планы',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('version_number', models.PositiveIntegerField(verbose_name='номер версии')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'На согласовании'), ('APPROVED', 'Утвержден'), ('REJECTED', 'Отклонен'), ('COMPLETED', 'Завершен')], default='DRAFT', max_length=20, verbose_name='статус')),
                ('is_baseline', models.BooleanField(default=False, verbose_name='базовый план')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='дата утверждения')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'версия плана',
                'verbose_name_plural': 'версии планов',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=50, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('year', models.PositiveIntegerField(verbose_name='год')),
                ('is_default', models.BooleanField(default=False, verbose_name='по умолчанию')),
            ],
            options={
                'verbose_name': 'производственный календарь',
                'verbose_name_plural': 'производственные календари',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('is_working', models.BooleanField(default=True, verbose_name='рабочий день')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='праздник')),
                ('is_shortened', models.BooleanField(default=False, verbose_name='сокращенный')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'день календаря',
                'verbose_name_plural': 'дни календаря',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='дата')),
                ('baseline_quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='базовый объем')),
                ('baseline_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='базовая стоимость')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'базовый план',
                'verbose_name_plural': 'базовые планы',
                'ordering': ['date'],
            },
        ),
    ]
