# Generated by Django 5.2.17 on 2026-10-04 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('planning', '0001_initial'),
        ('works', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybaseline',
            name='project_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='works.projectwork', verbose_name='работа'),
        ),
        migrations.AddField(
            model_name='dailybaseline',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='works.projectworkitem', verbose_name='элемент работы'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='works.projectworkitem', verbose_name='элемент работы'),
        ),
        migrations.AddField(
            model_name='loadprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='loadprofileitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='loadprofileitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.loadprofile', verbose_name='профиль'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='project_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='works.projectwork', verbose_name='работа'),
        ),
        migrations.AddField(
            model_name='planversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plan_versions', to=settings.AUTH_USER_MODEL, verbose_name='утверждено'),
        ),
        migrations.AddField(
            model_name='planversion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='planversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_versions', to=settings.AUTH_USER_MODEL, verbose_name='создано'),
        ),
        migrations.AddField(
            model_name='planversion',
            name='monthly_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='planning.monthlyplan', verbose_name='месячный план'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='plan_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='planning.planversion', verbose_name='версия плана'),
        ),
        migrations.AddField(
            model_name='dailybaseline',
            name='source_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_records', to='planning.planversion', verbose_name='источник'),
        ),
        migrations.AddField(
            model_name='productioncalendar',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planning.productioncalendar', verbose_name='календарь'),
        ),
        migrations.AlterUniqueTogether(
            name='loadprofile',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='loadprofileitem',
            unique_together={('profile', 'workday_number')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyplan',
            unique_together={('project_work', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='planversion',
            unique_together={('monthly_plan', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('plan_version', 'work_item', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailybaseline',
            unique_together={('project_work', 'work_item', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='productioncalendar',
            unique_together={('company', 'code', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='calendarday',
            unique_together={('calendar', 'date')},
        ),
    ]
