# Generated by Django 5.2.18 on 2026-10-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('planning', '0002_initial'),
        ('projects', '0001_initial'),
        ('works', '0003_projectworkitem_quantity_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'На согласовании'), ('APPROVED', 'Утвержден'), ('REJECTED', 'Отклонен'), ('COMPLETED', 'Завершен')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('snapshot', models.JSONField(default=dict, editable=False, verbose_name='Зафиксированный состав')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Глобальная версия объекта',
                'verbose_name_plural': 'Глобальные версии объектов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailybaseline',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='works.projectworkitem', verbose_name='элемент работы'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='works.projectworkitem', verbose_name='элемент работы'),
        ),
        migrations.AddConstraint(
            model_name='dailyplan',
            constraint=models.UniqueConstraint(condition=models.Q(('work_item__isnull', False)), fields=('plan_version', 'work_item', 'date'), name='unique_item_daily_plan'),
        ),
        migrations.AddConstraint(
            model_name='dailyplan',
            constraint=models.UniqueConstraint(condition=models.Q(('work_item__isnull', True)), fields=('plan_version', 'date'), name='unique_simple_daily_plan'),
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_global_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='construction_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.constructionobject', verbose_name='Строительный объект'),
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_global_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='planning.globalplanversion'),
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='source_versions',
            field=models.ManyToManyField(blank=True, related_name='global_versions', to='planning.planversion'),
        ),
        migrations.AlterUniqueTogether(
            name='globalplanversion',
            unique_together={('construction_object', 'version_number')},
        ),
    ]
