# Generated by Django 5.2.18 on 2026-10-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('planning', '0003_globalplanversion_alter_dailyplan_unique_together_and_more'),
        ('projects', '0001_initial'),
        ('resources', '0002_alter_equipmenttype_options_and_more'),
        ('works', '0004_projectwork_allow_fractional_projectwork_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalplanversion',
            name='planning_month',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемый месяц'),
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='scenario',
            field=models.CharField(blank=True, choices=[('REMAINING', 'Факт и распределение остатка'), ('BASELINE', 'Сохранение базового плана')], max_length=12, verbose_name='Сценарий'),
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='version_kind',
            field=models.CharField(choices=[('LEGACY', 'Сводная версия'), ('BASELINE', 'Базовый план периода'), ('FORECAST', 'Месячное уточнение периода')], default='LEGACY', max_length=12, verbose_name='Назначение'),
        ),
        migrations.CreateModel(
            name='PlanningWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Название плана')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('baseline_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseline_workspace', to='planning.globalplanversion', verbose_name='Базовая версия')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('construction_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.constructionobject', verbose_name='Строительный объект')),
            ],
            options={
                'verbose_name': 'Рабочее пространство планирования',
                'verbose_name_plural': 'Рабочие пространства планирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='planning.planningworkspace', verbose_name='Рабочее пространство'),
        ),
        migrations.CreateModel(
            name='ResourceMonthAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('month', models.DateField(help_text='Первое число месяца', verbose_name='Месяц')),
                ('kind', models.CharField(choices=[('labor', 'Люди'), ('equipment', 'Техника'), ('fuel', 'ГСМ')], max_length=12, verbose_name='Ресурс')),
                ('equipment_number', models.CharField(blank=True, max_length=50, verbose_name='Номер машины')),
                ('fuel_type', models.CharField(blank=True, choices=[('DIESEL', 'Дизельное топливо'), ('PETROL_92', 'Бензин АИ-92'), ('PETROL_95', 'Бензин АИ-95'), ('PETROL_98', 'Бензин АИ-98'), ('GAS', 'Газ'), ('OIL', 'Масло моторное'), ('OTHER', 'Другое')], max_length=20, verbose_name='Вид ГСМ')),
                ('equipment_ref', models.CharField(blank=True, max_length=150, verbose_name='Техника для ГСМ')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Численность / количество на рабочий день')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Часы за месяц')),
                ('liters', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Литры за месяц')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ставка за час / цена литра')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.brigade', verbose_name='Бригада')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.equipmenttype', verbose_name='Тип техники')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='planning.globalplanversion')),
            ],
            options={
                'ordering': ['month', 'kind', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'labor')), fields=('version', 'month', 'kind', 'brigade'), name='unique_workspace_labor_month'), models.UniqueConstraint(condition=models.Q(('kind', 'equipment')), fields=('version', 'month', 'kind', 'equipment_type', 'equipment_number'), name='unique_workspace_equipment_month'), models.UniqueConstraint(condition=models.Q(('kind', 'fuel')), fields=('version', 'month', 'kind', 'fuel_type', 'equipment_ref'), name='unique_workspace_fuel_month')],
            },
        ),
        migrations.CreateModel(
            name='WorkMonthAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('month', models.DateField(help_text='Первое число месяца', verbose_name='Месяц')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Объём основной работы')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('load_profile', models.ForeignKey(blank=True, help_text='Пустой выбор использует профили работы и подработ.', null=True, on_delete=django.db.models.deletion.PROTECT, to='planning.loadprofile', verbose_name='Профиль на месяц')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_allocations', to='planning.globalplanversion')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.projectwork', verbose_name='Работа')),
            ],
            options={
                'ordering': ['month', 'work__code', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('version', 'work', 'month'), name='unique_workspace_work_month')],
            },
        ),
    ]
