# Generated by Django 5.2.18 on 2026-10-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_globalplanversion_planning_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemonthallocation',
            name='load_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planning.loadprofile', verbose_name='Профиль ресурса на месяц'),
        ),
    ]
