# Generated by Django 5.2.18 on 2026-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_resourcemonthallocation_load_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadprofile',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='productioncalendar',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='код'),
        ),
    ]
