# Generated by Django 5.2.18 on 2026-10-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_alter_loadprofile_code_alter_productioncalendar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemonthallocation',
            name='equipment_ref',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='Техника для ГСМ'),
        ),
    ]
