# Generated by Django 5.2.18 on 2026-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_alter_resourcemonthallocation_equipment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemonthallocation',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Остаток на каждый день, л'),
        ),
        migrations.AlterField(
            model_name='resourcemonthallocation',
            name='liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Расход за месяц, л'),
        ),
    ]
