# Generated by Django 5.2.18 on 2026-10-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_resourcemonthallocation_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmonthallocation',
            name='item_quantities',
            field=models.JSONField(blank=True, default=dict, verbose_name='Месячные объёмы подработ'),
        ),
    ]
