# Generated by Django 5.2.18 on 2026-10-07 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_standard_roles'),
        ('planning', '0009_workmonthallocation_item_quantities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalplanversion',
            name='approval_round',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Раунд согласования'),
        ),
        migrations.CreateModel(
            name='GlobalPlanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('number', models.PositiveIntegerField(verbose_name='Раунд')),
                ('snapshot', models.JSONField(default=dict, editable=False, verbose_name='Согласуемый состав')),
                ('legacy_approved', models.BooleanField(default=False, editable=False, verbose_name='Историческое утверждение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_plan_reviews', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_rounds', to='planning.globalplanversion')),
            ],
            options={
                'verbose_name': 'Раунд согласования плана',
                'verbose_name_plural': 'Раунды согласования планов',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GlobalPlanDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('section', models.CharField(choices=[('PRODUCTION', 'Работы'), ('HR', 'Люди'), ('TECH', 'Техника и ГСМ'), ('CEO', 'Генеральный директор'), ('PLANNER', 'Подготовка')], max_length=20, verbose_name='Раздел')),
                ('action', models.CharField(choices=[('SUBMIT', 'Отправлен'), ('APPROVE', 'Согласовано'), ('REJECT', 'Возвращён на доработку'), ('COMPLETE', 'Завершён')], max_length=20, verbose_name='Решение')),
                ('actor_name', models.CharField(max_length=300, verbose_name='Пользователь')),
                ('actor_role', models.CharField(max_length=50, verbose_name='Роль на момент решения')),
                ('comment', models.TextField(blank=True, max_length=4000, verbose_name='Комментарий')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_plan_decisions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='planning.globalplanreview')),
            ],
            options={
                'verbose_name': 'Решение по плану',
                'verbose_name_plural': 'Решения по планам',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='globalplanversion',
            name='baseline_review',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_versions', to='planning.globalplanreview', verbose_name='Зафиксированная база'),
        ),
        migrations.AddConstraint(
            model_name='globalplanreview',
            constraint=models.UniqueConstraint(fields=('version', 'number'), name='unique_global_review_round'),
        ),
        migrations.AddConstraint(
            model_name='globalplandecision',
            constraint=models.UniqueConstraint(condition=models.Q(('action', 'APPROVE')), fields=('review', 'section'), name='unique_section_review_approval'),
        ),
    ]
