# Generated by Django 5.2.18 on 2026-10-07 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_approval_roles'),
        ('planning', '0011_preserve_legacy_reviews'),
        ('projects', '0002_alter_constructionobject_code_alter_project_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('FIXED', 'Зафиксирована')], default='DRAFT', max_length=10, verbose_name='Статус')),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_plans', to=settings.AUTH_USER_MODEL)),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_project_plans', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='planning.projectplanversion', verbose_name='Предыдущая сводная версия')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidated_plans', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Сводная версия плана проекта',
                'verbose_name_plural': 'Сводные версии планов проектов',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPlanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('construction_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_plan_members', to='projects.constructionobject')),
                ('review', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_plan_members', to='planning.globalplanreview')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_plan_members', to='planning.globalplanversion', verbose_name='Версия плана объекта')),
                ('consolidated_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='planning.projectplanversion')),
            ],
            options={
                'verbose_name': 'Объект сводной версии проекта',
                'verbose_name_plural': 'Объекты сводной версии проекта',
                'ordering': ['construction_object__name', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectplanversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='unique_project_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='projectplanmember',
            constraint=models.UniqueConstraint(fields=('consolidated_version', 'construction_object'), name='unique_object_in_project_plan'),
        ),
    ]
