# Generated by Django 5.2.18 on 2026-10-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_projectplanversion_projectplanmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmonthallocation',
            name='daily_override',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Сохранённый дневной план объединения'),
        ),
    ]
