# Generated by Django 5.2.17 on 2026-10-04 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Обновление'), ('DELETE', 'Удаление'), ('SUBMIT', 'Отправка на согласование'), ('APPROVE', 'Утверждение'), ('REJECT', 'Отклонение'), ('REVISION', 'Создание ревизии'), ('GENERATE', 'Генерация плана')], max_length=50, verbose_name='действие')),
                ('entity_type', models.CharField(max_length=100, verbose_name='тип объекта')),
                ('entity_id', models.CharField(max_length=100, verbose_name='ID объекта')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='старое значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='новое значение')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'запись аудита',
                'verbose_name_plural': 'записи аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
