# Generated by Django 5.2.18 on 2026-10-08 20:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_approval_roles'),
        ('planning', '0013_workmonthallocation_daily_override'),
        ('resources', '0007_brigade_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('start', models.DateField(verbose_name='Начало периода')),
                ('end', models.DateField(verbose_name='Конец периода')),
                ('demand', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.globalplanversion', verbose_name='Версия общего плана')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RotationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('on_days', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Дней на вахте')),
                ('off_days', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Дней отдыха')),
                ('anchor', models.DateField(verbose_name='Начало графика должности')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.brigade', verbose_name='Должность')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='rotation.rotationplan')),
            ],
            options={
                'ordering': ['brigade__name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RotationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='Обозначение человека')),
                ('on_days', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Дней на вахте')),
                ('off_days', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Дней отдыха')),
                ('anchor', models.DateField(verbose_name='Дата начала вахты')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='rotation.rotationrole')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='rotationrole',
            constraint=models.UniqueConstraint(fields=('plan', 'brigade'), name='rotation_unique_position'),
        ),
    ]
