# Generated by Django 5.2.18 on 2026-10-08 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_approval_roles'),
        ('rotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('day', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('ON', 'Вахта'), ('OFF', 'Отдых')], max_length=3, verbose_name='Статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='rotation.rotationperson')),
            ],
            options={
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('person', 'day'), name='rotation_unique_person_day')],
            },
        ),
    ]
